#!/bin/bash 

echo "======= Create User ======="
read  -p "Enter the username:" username
read  -p "Enter the password:" password

# this is creating user 
sudo useradd -m $username

# this is setting the password -e is setting for this enviroment 
echo -e "$password\n$password" | sudo passwd $username

echo "===== Usr created======"

 
